version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_test

      DATABASE_URL: postgres://user:pass@postgres:5432/db_test
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
      - '9229:9229'
    command: npm run start-dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:12.2
    ports:
      - '35432:5432'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_test
